## Ćw1. PyTorch Zadania

### 1. Czytanie dokumentacji 

Dużą częścią głębokiego uczenia się (i ogólnie nauki kodowania) jest zapoznanie się z dokumentacją określonego frameworka. Będziemy często korzystać z dokumentacji PyTorch. Poświęć 10 minut na przeczytanie poniższych informacji:
  * Dokumentacja na temat [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * Dokumentacja [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).

### 2. Utwórz losowy tensor o kształcie `(7, 7)`.

In [1]:
# Zaimportuj torch
import torch

# Utwórz losowy tensor
my_tensor = torch.rand(7, 7)
my_tensor

tensor([[0.9987, 0.6327, 0.9954, 0.2622, 0.8971, 0.6425, 0.0731],
        [0.7296, 0.7042, 0.9000, 0.7358, 0.0533, 0.9143, 0.6248],
        [0.4308, 0.7359, 0.8781, 0.8870, 0.5536, 0.6964, 0.4129],
        [0.4385, 0.0396, 0.9953, 0.0248, 0.1760, 0.0368, 0.2513],
        [0.8809, 0.4008, 0.3558, 0.8641, 0.4979, 0.4724, 0.3740],
        [0.4882, 0.7455, 0.9199, 0.7922, 0.5725, 0.9582, 0.9960],
        [0.1500, 0.4996, 0.4920, 0.8531, 0.0463, 0.1183, 0.0127]])

In [2]:


# Utwórz losowy tensor


### 3. Wykonaj mnożenie macierzowe na tensorze z punktu 2 z innym losowym tensorem o kształcie `(1, 7)` (wskazówka: może być konieczna transpozycja drugiego tensora).

In [3]:
# Utwórz kolejny losowy tensor
next_tensor = torch.rand(1, 7)
# Wykonaj mnożenie macierzowe
result = torch.matmul(my_tensor, next_tensor.T)
result

tensor([[2.5009],
        [3.4143],
        [3.2136],
        [1.3150],
        [2.3276],
        [3.9472],
        [1.6501]])

### 4. Ustaw losowe ziarno na `0` i wykonaj 2 i 3 od nowa.

Wynik powinien być następujący:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Ustaw ręczne ziarno
torch.manual_seed(0)

# Utwórz dwa losowe tensory
tensor1 = torch.rand(7, 7)
tensor2 = torch.rand(1, 7)

# Mnożenie tensorów przez macierz
result = torch.matmul(tensor1, tensor2.T)
result

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Wiemy, jak ustawić je za pomocą `torch.manual_seed()`, ale czy istnieje odpowiednik GPU? (wskazówka: zajrzyj do dokumentacji dla `torch.cuda`)
  * Jeśli tak, ustaw losowe ziarno GPU na `1234`.

In [5]:
# Ustaw losowe ziarno na GPU
# cuda = torch.device('cuda')
torch.cuda.manual_seed(0)
torch.rand(7, 7).cuda()

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx


### 6. Utwórz dwa losowe tenosry o kształcie `(2, 3)` i wyślij  do GPU (będzie potrzebny  dostęp do GPU). Ustaw `torch.manual_seed(1234)` podczas tworzenia tensorów (nie musi to być losowe ziarno GPU). Wynik powinien wyglądać mniej więcej tak:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Ustaw losowe ziarno
torch.manual_seed(1234)

# Sprawdź dostęp do GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Utwórz dwa losowe tensory na GPU
tensor1 = torch.rand(2, 3, device=device)
tensor2 = torch.rand(2, 3, device=device)

tensor1, tensor2

Using device: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))


### 7. Wykonaj mnożenie macierzy na tensorach utworzonych w punkcie 6 (ponownie może być konieczne dostosowanie kształtu jednego z tensorów).

Wynik powinien wyglądać następująco:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Wykonaj matmul na tensor_A and tensor_B
matmul = torch.matmul(tensor1, tensor2.T)

### 8. Znajdź maximum i minimum wyników 7.

In [ ]:
# Wyznacz max
max = torch.max(matmul)
# Wyznacz min
min = torch.min(matmul)

max, min

(tensor(0.7668, device='cuda:0'), tensor(0.2786, device='cuda:0'))

### 9. Znajdź maksymalną i minimalną wartość indeksu wyniku 7.

In [ ]:
# Wyznacz arg max
max_idx = torch.argmax(matmul)

# Wyznacz arg min
min_idx = torch.argmin(matmul)

max_idx, min_idx


(tensor(1, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Utwórz losowy tensor o kształcie `(1, 1, 1, 10)`, a następnie utwórz nowy tensor z usuniętymi wszystkimi wymiarami `1`, aby otrzymać tensor o kształcie `(10)`. Ustaw ziarno na `7` podczas tworzenia i wypisz pierwszy tensor i jego kształt, a także drugi tensor i jego kształt.

Wynik powinien być:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Ustaw ziarno

torch.manual_seed(7)

# Utwórz losowy tensor
rand_tensor = torch.rand(1, 1, 1, 10)

# Usuń pojedynczy wymiar
rand_tensor_squeezed = rand_tensor.squeeze()

# Wydrukuj tensory i ich kształty
rand_tensor, rand_tensor_squeezed

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]))